import ida_idaapi
import idc
import ida_kernwin
import ida_bytes
import csv

global_offset = 0x7100000000

def update_symbol_name(address, new_name):
    address += global_offset

    current_name = idc.get_name(address, idc.GN_VISIBLE)
    if current_name != new_name:
        # automatically rename autogenerated names
        if current_name.startswith(("sub_", "off_", "qword_", "dword_", "unk_")):
            idc.set_name(address, new_name, idc.SN_NOWARN | idc.SN_NOCHECK)
        else:
            choice = ida_kernwin.ask_yn(0, f"Do you want to update symbol at {hex(address)} from '{current_name}' to '{new_name}'?")
            if choice == ida_kernwin.ASKBTN_YES:
                idc.set_name(address, new_name, idc.SN_NOWARN | idc.SN_NOCHECK)

def import_symbols_from_csv(csv_file):
    with open(csv_file, 'r') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            address = int(row["Address"], 16)
            name = row["Name"]
            update_symbol_name(address, name)

def import_symbols():
    csv_file_path = ida_kernwin.ask_file(False, "symbols.txt", "Import symbols")
    if csv_file_path:
        import_symbols_from_csv(csv_file_path)
        print("Symbols imported.")

import_symbols()